### ISSUE TITLE
WLAN Strength Indicator

### ISSUE THREAD

**Issue by tempo3** [mfdlr/homeassistant-wlanthermo#1]
Thanks a lot for this great integration. It works perfectly! Can you please add the sensor for the WIFI signal strength? This would be super. Thanks a lot in advance.
Axel

**Comment by mfdlr** [comment]
This should do:

```
- platform: template
  sensors:
    # Wifi signal strength
    wlanthermo_signal_strength:
      value_template: "{{ state_attr('sensor.wlanthermo', 'system')['rssi'] }}"
      unit_of_measurement: "dBm"
      device_class: signal_strength
      entity_id: sensor.wlanthermo
```
